"""The verifier confusion matrix: evidence for H2b.

Section 13 asks for a *confusion matrix over labelled leaking and valid programs, including
false-rejection rate, by diagnostic code*. This module computes it from a labelled corpus and
emits it as a machine-readable artifact, so the manuscript's rejection-breakdown figure is
generated by a script rather than transcribed (section 12).

**Why the false-rejection rate is the load-bearing number.** A verifier that rejected every
program would detect every leak. The leak-detection rate alone is therefore not evidence of
anything; it means something only beside the rate at which sound programs are turned away.
The corpus is weighted accordingly — more valid programs than leaking ones, chosen to press
on the verifier's edges rather than to be comfortably typical.

**Why there are three labels, not two.** Pooling malformed programs with leaking ones would
flatter the headline number. A model that misnames an operator is failing at output
conformance and is fixed by better constrained decoding; a model that writes a
forward-reaching lag is failing at temporal reasoning, which is the failure this project
claims to catch. They are reported separately because they call for different responses.

**Why the leaking corpus is short.** Most leaks an unrestricted-Python feature generator can
express have no encoding in this DSL at all — they are prevented by construction rather than
rejected by analysis, and so cannot appear in a corpus of writable programs.
:data:`UNREPRESENTABLE_LEAKS` records them, because "the verifier caught 12 of 12" understates
the claim if the reason there are only 12 goes unstated.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

import yaml

from vifusion.compiler.compile import CompileResult, compile_program, parse_program
from vifusion.compiler.diagnostics import Code, DiagnosticFamily

Label = Literal["valid", "leaking", "invalid"]

UNREPRESENTABLE_LEAKS: tuple[dict[str, str], ...] = (
    {
        "leak": "Reading a row at a later index",
        "python": "df['temp'].shift(-1), or any positive lookahead on a sorted frame",
        "why_unrepresentable": (
            "There are no rows and no index. A feature addresses a stream by event time "
            "through an operator whose reach is a declared duration, and the only operator "
            "that names an instant is `lag`, whose sign is checked."
        ),
    },
    {
        "leak": "Joining on event time instead of availability",
        "python": "pd.merge_asof(left, right, on='event_time')",
        "why_unrepresentable": (
            "There is no join. Eligibility is enforced once by the replay clock, and an "
            "operator reads only buffers the clock has already released, so a program has "
            "no way to address a record that has not arrived."
        ),
    },
    {
        "leak": "Fitting a transform on the whole column",
        "python": "StandardScaler().fit(df['temp']) then transforming every row",
        "why_unrepresentable": (
            "There is no whole column. Every aggregate is bounded by a declared trailing "
            "window, and an unbounded aggregate has no encoding."
        ),
    },
    {
        "leak": "Resampling or interpolating across a gap",
        "python": "df.resample('1h').interpolate()",
        "why_unrepresentable": (
            "Interpolation between two observations uses the later one, so filling a gap at "
            "time t consumes information from after t. No operator interpolates; a gap is "
            "reported by `missing_count` and `staleness` rather than filled."
        ),
    },
    {
        "leak": "Using the target's future value",
        "python": "df['y'].rolling(3).mean() computed over the full frame",
        "why_unrepresentable": (
            "Labels enter the replay queue as reveal events gated on label_available_time, "
            "so a feature over the target obeys the same clock as any other stream."
        ),
    },
    {
        "leak": "Selecting a forecast issued after the prediction time",
        "python": "group by valid_time, take the last issue",
        "why_unrepresentable": (
            "The forecast selector takes the latest *eligible* issue; issues the clock has "
            "not released are not in the state it reads from."
        ),
    },
    {
        "leak": "Arbitrary code with an arbitrary data reference",
        "python": "any expression closing over the enclosing DataFrame",
        "why_unrepresentable": (
            "The DSL is a dataflow graph of registered operators over declared sources. No "
            "generated string reaches an interpreter, which is also why prompt injection "
            "through dataset metadata is structurally contained (section 7.2)."
        ),
    },
)
"""Leaks that a Python-emitting feature generator can write and this DSL cannot express.

Contribution 2 of docs/novelty.md in concrete form: streaming execution as normative
semantics makes an ineligible dependency *unrepresentable* rather than merely rejected. Each
entry names a leak, the idiom that produces it in an unrestricted setting, and the structural
reason it has no encoding here.
"""


@dataclass(frozen=True)
class CorpusProgram:
    """One labelled program in the audit corpus."""

    name: str
    label: Label
    description: str
    payload: dict[str, Any]
    expected_family: DiagnosticFamily | None = None
    expected_code: Code | None = None
    source_file: str = ""

    def __str__(self) -> str:
        return self.name


@dataclass
class ConfusionMatrix:
    """Outcomes of compiling a labelled corpus."""

    accepted: Counter[Label] = field(default_factory=Counter)
    rejected: Counter[Label] = field(default_factory=Counter)
    by_code: Counter[str] = field(default_factory=Counter)
    wrong_family: list[str] = field(default_factory=list)
    false_rejections: list[str] = field(default_factory=list)
    false_acceptances: list[str] = field(default_factory=list)

    def total(self, label: Label) -> int:
        return self.accepted[label] + self.rejected[label]

    @property
    def false_rejection_rate(self) -> float:
        """Sound programs turned away. The number that keeps the headline honest."""
        total = self.total("valid")
        return self.rejected["valid"] / total if total else 0.0

    @property
    def leak_detection_rate(self) -> float:
        """Leaking programs rejected. Meaningless without the rate above."""
        total = self.total("leaking")
        return self.rejected["leaking"] / total if total else 0.0

    @property
    def invalid_detection_rate(self) -> float:
        total = self.total("invalid")
        return self.rejected["invalid"] / total if total else 0.0

    def as_dict(self) -> dict[str, Any]:
        return {
            "counts": {
                label: {
                    "total": self.total(label),
                    "accepted": self.accepted[label],
                    "rejected": self.rejected[label],
                }
                for label in ("valid", "leaking", "invalid")
            },
            "rates": {
                "false_rejection": self.false_rejection_rate,
                "leak_detection": self.leak_detection_rate,
                "invalid_detection": self.invalid_detection_rate,
            },
            "rejections_by_code": dict(sorted(self.by_code.items())),
            "false_rejections": sorted(self.false_rejections),
            "false_acceptances": sorted(self.false_acceptances),
            "wrong_family": sorted(self.wrong_family),
            "unrepresentable_leaks": [dict(entry) for entry in UNREPRESENTABLE_LEAKS],
        }


def load_corpus(directory: Path) -> list[CorpusProgram]:
    """Read every labelled program, expanding each file's shared sources into it.

    Sources and calendars are declared once per file and shared, so a program in the corpus
    reads as the few nodes that distinguish it rather than as a wall of boilerplate. The
    corpus is evidence a reviewer should be able to audit by eye.
    """
    programs: list[CorpusProgram] = []
    for path in sorted(directory.glob("*.yaml")):
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
        label: Label = document["family"]
        shared_sources = document.get("sources", [])
        shared_calendars = document.get("calendars", {})
        for entry in document["programs"]:
            payload: dict[str, Any] = {
                "schema_version": "0.1.0",
                "name": entry["name"],
                "sources": shared_sources,
                "calendars": shared_calendars,
                "nodes": entry["nodes"],
                "outputs": entry["outputs"],
            }
            programs.append(
                CorpusProgram(
                    name=entry["name"],
                    label=label,
                    description=entry.get("description", ""),
                    payload=payload,
                    expected_family=(
                        DiagnosticFamily(entry["expected_family"])
                        if "expected_family" in entry
                        else None
                    ),
                    expected_code=(
                        Code(entry["expected_code"]) if "expected_code" in entry else None
                    ),
                    source_file=path.name,
                )
            )
    names = [program.name for program in programs]
    duplicates = {name for name in names if names.count(name) > 1}
    if duplicates:
        raise ValueError(f"duplicate program names in the corpus: {sorted(duplicates)}")
    return programs


def compile_corpus_program(program: CorpusProgram) -> CompileResult:
    """Compile one corpus entry exactly as the proposal loop would."""
    from vifusion.runtime.batch import BATCH_LOWERINGS

    parsed, diagnostics = parse_program(program.payload)
    if parsed is None:
        return CompileResult(status="rejected", diagnostics=tuple(diagnostics))
    return compile_program(parsed, batch_lowerings=BATCH_LOWERINGS)


def audit(programs: list[CorpusProgram]) -> ConfusionMatrix:
    """Compile every labelled program and tally the outcomes."""
    matrix = ConfusionMatrix()
    for program in programs:
        result = compile_corpus_program(program)
        if result.accepted:
            matrix.accepted[program.label] += 1
            if program.label != "valid":
                matrix.false_acceptances.append(program.name)
            continue

        matrix.rejected[program.label] += 1
        for diagnostic in result.diagnostics:
            matrix.by_code[diagnostic.code.value] += 1
        if program.label == "valid":
            matrix.false_rejections.append(
                f"{program.name}: {'; '.join(str(d) for d in result.diagnostics)}"
            )
        elif program.expected_family is not None:
            families = {diagnostic.family for diagnostic in result.diagnostics}
            if program.expected_family not in families:
                matrix.wrong_family.append(
                    f"{program.name}: expected {program.expected_family.value}, "
                    f"got {sorted(family.value for family in families)}"
                )
    return matrix


def summarise(matrix: ConfusionMatrix) -> str:
    """A readable rendering of the matrix for the terminal."""
    lines = ["label      total  accepted  rejected"]
    for label in ("valid", "leaking", "invalid"):
        lines.append(
            f"{label:<10} {matrix.total(label):>5}  {matrix.accepted[label]:>8}  "
            f"{matrix.rejected[label]:>8}"
        )
    lines.extend(
        [
            "",
            f"false rejection rate  {matrix.false_rejection_rate:.1%}",
            f"leak detection rate   {matrix.leak_detection_rate:.1%}",
            f"invalid detection     {matrix.invalid_detection_rate:.1%}",
            "",
            "rejections by code",
        ]
    )
    for code, count in sorted(matrix.by_code.items()):
        lines.append(f"  {code:<16} {count}")
    if matrix.false_rejections:
        lines.append("")
        lines.append("FALSE REJECTIONS")
        lines.extend(f"  {entry}" for entry in matrix.false_rejections)
    if matrix.false_acceptances:
        lines.append("")
        lines.append("FALSE ACCEPTANCES")
        lines.extend(f"  {entry}" for entry in matrix.false_acceptances)
    lines.append("")
    lines.append(
        f"leaks prevented by construction, not analysis: {len(UNREPRESENTABLE_LEAKS)} "
        "(see UNREPRESENTABLE_LEAKS)"
    )
    return "\n".join(lines)
